name: dev

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: laughedelic/coursier-setup@v1
        with:
          jvm: "temurin:1.17 --jvm-index https://raw.githubusercontent.com/coursier/jvm-index/master/index.json"
          apps: sbt sbtn
      - uses: coursier/cache-action@v5

      - name: Tests
        run: sbt test
