name: dev

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: laughedelic/coursier-setup@v1
        with:
          jvm: openjdk:1.17.0
          apps: sbt sbtn
      - uses: coursier/cache-action@v5

      - name: Tests
        run: sbt test
