name: dev

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: coursier/setup-action@v1.2.0-M2
        with:
          jvm: temurin:1.17
          apps: sbt sbtn
      - uses: coursier/cache-action@v6

      - name: Tests
        run: sbt test
